### ISSUE TITLE
FracdiffStat Error: TypeError: '(slice(None, None, None), 0)' is an invalid key

### ISSUE THREAD

**Issue by jmrichardson** [fracdiff/fracdiff#63]
Hi, wow, this lib is awesomely fast!  I did run into a problem though with FracdiffStat (Fracdiff worked):
```

f = FracdiffStat()
d = f.fit_transform(data)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pa\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-4285a9949507>", line 1, in <module>
    d = f.fit_transform(data)
  File "D:\Anaconda3\envs\pa\lib\site-packages\sklearn\base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "D:\Anaconda3\envs\pa\lib\site-packages\fracdiff\fracdiffstat.py", line 117, in fit
    self.d_ = self._find_features_d(X)
  File "D:\Anaconda3\envs\pa\lib\site-packages\fracdiff\fracdiffstat.py", line 165, in _find_features_d
    return numpy.array(list(d_))
  File "D:\Anaconda3\envs\pa\lib\site-packages\fracdiff\fracdiffstat.py", line 155, in <genexpr>
    features = (X[:, i] for i in range(X.shape[1]))
  File "C:\Users\john\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\john\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 75, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(slice(None, None, None), 0)' is an invalid key
```

Thanks for any help

**Comment by ghost** [comment]
Thanks for using it and reporting an issue!

I guess `data` is pandas dataframe. X in FracdiffStat is supposed to be numpy array.

**Comment by jmrichardson** [comment]
That was it!  Thank you and really do appreciate this work! 👍

**Comment by ghost** [comment]
@jmrichardson 
FracdiffStat in the latest fracdiff now accepts pandas.DataFrame (it returns np.ndarray though). Thanks for reporting!
